services:
  app:
    build:
      context: .
    container_name: domain-detection-api
    # restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/domain_detection?sslmode=disable
      - JWT_SECRET=change-this-in-production
      - ENCRYPTION_KEY=change-this-in-production
      - ENVIRONMENT=development
      # Add the Uptrends API credentials
      - UPTRENDS_API_KEY=BYRJFE2XNnLRzLaYIKY6/TdeTjxCw11j
      - UPTRENDS_USERNAME=4ab357f5ee1d4581a0fdb8607b06b306
      - UPTRENDS_API_URL=https://api.uptrends.com/v4
      - TELEGRAM_BOT_TOKEN=7762941862:AAGW96BmgkGouDpgAYJxITCOISLuOrXX_4Y
      - SITE24X7_CLIENT_ID=1000.F8TO5JEX91VJNSPAPCD5TF40RWUE6K
      - SITE24X7_CLIENT_SECRET=2a48584831dc1a3de4c1adc4d0efacafa7a63aaa4b
      - SITE24X7_REFRESH_TOKEN=1000.aab35db7ef1b9a6eca0c48593f98144e.ac5b0a7ddb2c9e21cab10814bb2895ae
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - domain-detection-network

  db:
    image: postgres:16-alpine
    container_name: domain-detection-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=domain_detection
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - domain-detection-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: migrate/migrate:v4.16.2
    container_name: domain-detection-migrations
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    networks:
      - domain-detection-network
    command: ["-path", "/migrations", "-database", "postgres://postgres:postgres@db:5432/domain_detection?sslmode=disable", "up"]
    # docker-compose run --rm migrations

networks:
  domain-detection-network:
    driver: bridge

volumes:
  postgres_data: